import "./globals.css";
import Link from "next/link";

export const metadata = {
  title: "This is BoBae App",
  description: "Generated by create next app",
};
About();
export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <h1>vercel에 올라간거 확인 레이아웃 보배사이트</h1>
        <h3>
          <Link href="/">메인</Link>
        </h3>
        {children}
      </body>
    </html>
  );
}
